server:
  port: 9800

servlet:
  session:
    timeout: 1800

spring:
  datasource:
    url: jdbc:mysql://vicondb.cgv0roelzivs.ap-northeast-2.rds.amazonaws.com:3306/dev?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: admin
    password: ejrrl7748*
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

cloud:
  aws:
    s3:
      bucket: vicon-static-bucket
    region:
      static: ap-northeast-2
    credentials:
      accessKey: AKIAUX6UDD36IURRQO65
      secretKey: 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
    stack:
      auto: false

cdn:
  path: https://vicon-static-bucket.s3.ap-northeast-2.amazonaws.com

logging:
  level:
    org.springframework.web: DEBUG
    com.vicon: DEBUG